mango-analytics/tarificador/accounts/urls.py
from django.conf.urls import patterns, url

from accounts import views

urlpatterns = patterns('',
	url(r'login$', views.index, name='login'),
	url(r'login/log$', views.log, name='log'),
	url(r'login/logged/lo$', views.details, name='lo'),
)

mango-analytics/tarificador/tarifica/urls.py
from django.conf.urls import patterns, url
from tarifica.views import bundles, destinationGroups, general, providers, \
   trunks, users, wizard, config, pinsets, cdr, security

urlpatterns = patterns('',
   url(r'^login$', security.login_view, name='login'),
   url(r'^logout$', security.logout_view, name='logout'),

   url(r'^$', general.setup, name = 'setup'),
   url(r'^setup$', general.setup, name = 'setup'),
   url(r'^privacy$', general.privacy, name = 'privacy'),
   url(r'^manual$', general.manual, name = 'manual'),
   
   url(r'^config$', config.config, name = 'config'),
   url(r'^config/update/(?P<option>\w+)$', config.updateUser, name = 'config_update_user'),

   url(r'^providers/create/(?P<asterisk_id>\d+)$', providers.createProvider, name = 'providers_create'),
   url(r'^providers/update/(?P<provider_id>\d+)$', providers.updateProvider, name = 'providers_update'),
   url(r'^providers/delete/(?P<provider_id>\d+)$', providers.deleteProvider, name = 'providers_delete'),
   url(r'^providers/(?P<provider_id>\d+)$', providers.getProvider, name = 'providers_get'),
   
   url(r'^destinations/create/(?P<provider_id>\d+)$', destinationGroups.createDestinationGroup, name = 'destinations_create'),
   url(r'^destinations/update/(?P<destination_group_id>\d+)$', destinationGroups.updateDestinationGroup, name = 'destinations_update'),
   url(r'^destinations/delete/(?P<destination_group_id>\d+)$', destinationGroups.deleteDestinationGroup, name = 'destinations_delete'),
   
   url(r'^bundles/create/(?P<destination_group_id>\d+)$', bundles.createBundle, name = 'bundles_create'),
   url(r'^bundles/update/(?P<bundle_id>\d+)$', bundles.updateBundle, name = 'bundles_update'),
   url(r'^bundles/delete/(?P<bundle_id>\d+)$', bundles.deleteBundle, name = 'bundles_delete'),

   url(r'^trunks$', trunks.general, name = 'trunks'),
   url(r'^trunks/(?P<period_id>\w+)$', trunks.general, name = 'trunks_period'),
   url(r'^trunks/get/(?P<provider_id>\d+)$', trunks.getTrunk, name = 'trunks_get'),
   url(r'^trunks/get/(?P<provider_id>\d+)/(?P<period_id>\w+)$', trunks.getTrunk, name = 'trunks_get_period'),
   url(r'^trunks/download/(?P<provider_id>\d+)/(?P<start_date>[A-Za-z0-9_\-]+)/(?P<end_date>[A-Za-z0-9_\-]+)$', trunks.downloadTrunkCDR, name = 'trunks_download_cdr'),

   url(r'^realtime$', general.realtime, name = 'realtime'),
   url(r'^realtime/(?P<action>\w+)$', general.realtime, name = 'realtime'),

   url(r'^dashboard$', general.dashboard, name = 'dashboard'),
   
   url(r'^cdr$', cdr.general, name = 'cdr'),
   url(r'^cdr/page/(?P<page>\w+)$', cdr.general, name = 'cdr'),

   url(r'^users/general$', users.generalUsers, name = 'users_general'),
   url(r'^users/general/(?P<period_id>\w+)$', users.generalUsers, name = 'users_general_period'),
   url(r'^users/detail/(?P<extension_id>\d+)$', users.detailUsers, name = 'users_detail'),
   url(r'^users/detail/(?P<extension_id>\d+)/(?P<period_id>\w+)$', users.detailUsers, name = 'users_detail_period'),
   url(r'^users/analytics/(?P<extension_id>\d+)$', users.analyticsUsers, name = 'users_analytics'),
   url(r'^users/analytics/(?P<extension_id>\d+)/(?P<period_id>\w+)$', users.analyticsUsers, name = 'users_analytics_period'),

   url(r'^wizard/start$', wizard.start, name = "wizard_start"),
   url(r'^wizard/start/(?P<page>\d+)$', wizard.start, name = "wizard_start"),
   url(r'^wizard/testRun$', wizard.testrun, name = "wizard_test_run"),
   url(r'^wizard/testRun/(?P<default>\w+)$', wizard.testrun, name = "wizard_test_run"),
   url(r'^wizard/checkTestRunStatus$', wizard.checkTestRunStatus, name = "wizard_check_test_run_status"),
   url(r'^wizard/checkTestRunStatus/(?P<action>\w+)$', wizard.checkTestRunStatus, name = "wizard_check_test_run_status"),
   url(r'^wizard/results$', wizard.results, name = "wizard_results"),
   url(r'^wizard/run$', wizard.run, name = "wizard_run"),
   url(r'^wizard/run/(?P<default>\w+)$', wizard.run, name = "wizard_run"),
   url(r'^wizard/checkProcessingStatus$', wizard.checkProcessingStatus, name = "wizard_check_processing_status"),
   url(r'^wizard/checkProcessingStatus/(?P<action>\w+)$', wizard.checkProcessingStatus, name = "wizard_check_processing_status"),

   url(r'^pinsets/general$', pinsets.generalPinsets, name = 'pinsets_general'),
   url(r'^pinsets/general/(?P<period_id>\w+)$', pinsets.generalPinsets, name = 'pinsets_general_period'),
   url(r'^pinsets/detail/(?P<pinset_id>\d+)$',pinsets.detailPinsets, name = 'pinsets_detail'),
   url(r'^pinsets/detail/(?P<pinset_id>\d+)/(?P<period_id>\w+)$', pinsets.detailPinsets, name = 'pinsets_detail_period'),
   url(r'^pinsets/analytics/(?P<pinset_id>\d+)$', pinsets.analyticsPinsets, name = 'pinsets_analytics'),
   url(r'^pinsets/analytics/(?P<pinset_id>\d+)/(?P<period_id>\w+)$', pinsets.analyticsPinsets, name = 'pinsets_analytics_period'),
)

mango-analytics/tarificador/tarificador/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'tarificador.views.home', name='home'),
    # url(r'^tarificador/', include('tarificador.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^accounts/', include('accounts.urls',namespace="accounts")),
    url(r'^', include('tarifica.urls',namespace="tarifica")),
    url(r'^users/', include(admin.site.urls)),
)

mango-analytics/tarificador/tarifica/models.py
from django.db import models
from tarifica.django_countries.fields import CountryField

# Create your models here.
class PaymentType(models.Model):
    name = models.CharField(max_length = 255, default="Pospago")
    def __unicode__(self):
        return self.name

class TariffMode(models.Model):
    name = models.CharField(max_length = 255)
    def __unicode__(self):
        return self.name

class Provider(models.Model):
    asterisk_id = models.IntegerField()
    asterisk_name = models.CharField(max_length = 255)
    asterisk_channel_id = models.CharField(max_length=255)
    name = models.CharField(max_length = 255)
    monthly_cost = models.FloatField(default=0)
    provider_tech = models.CharField(max_length = 50, blank=True)
    payment_type = models.ForeignKey(PaymentType, blank=True, null=True)
    channels = models.IntegerField(blank=True, default=0)
    period_end = models.IntegerField(default=0)
    is_configured = models.BooleanField(default=False)
    def __unicode__(self):
        return self.asterisk_name

class DestinationName(models.Model):
    name = models.CharField(max_length = 255)
    def __unicode__(self):
        return self.name

class DestinationGroup(models.Model):
    provider = models.ForeignKey(Provider, blank=True, null=True)
    prefix = models.CharField(max_length = 255, blank=True, default="")
    notes = models.TextField(null=True, blank=True)
    connection_fee = models.FloatField()
    minute_fee = models.FloatField(default=60)
    billing_interval = models.IntegerField()
    destination_name = models.ForeignKey(DestinationName, blank=True, null=True)
    destination_country = CountryField(max_length = 6)
    has_bundles = models.BooleanField(default=False)
    def __unicode__(self):
        return f'{self.provider.name}-{self.destination_name.name}'

class Bundle(models.Model):
    name = models.CharField(max_length = 255)
    destination_group = models.ForeignKey(DestinationGroup, blank=True, null=True)
    tariff_mode = models.ForeignKey(TariffMode, blank=True, null=True)
    cost = models.FloatField()
    usage = models.IntegerField(blank=True, null=True, default=0)
    virtual_usage = models.IntegerField(blank=True, null=True, default=0)
    amount = models.IntegerField()
    priority = models.IntegerField()
    is_active = models.BooleanField(default=True)
    start_date = models.DateField()
    end_date = models.DateField()

class Call(models.Model):
    dialed_number = models.CharField(max_length = 255)
    extension_number = models.CharField(max_length = 255)
    pinset_number = models.CharField(max_length = 255)
    asterisk_unique_id = models.CharField(max_length = 255)
    duration = models.IntegerField()
    cost = models.FloatField()
    date = models.DateTimeField()
    destination_group = models.ForeignKey(DestinationGroup, blank=True, null=True)
    provider = models.ForeignKey(Provider, blank=True, null=True)

class Pinset(models.Model):
    pinset_number = models.CharField(max_length = 255)

class Extension(models.Model):
    extension_number = models.CharField(max_length = 255)
    name = models.CharField(max_length = 255)

class UserDailyDetail(models.Model):
    extension = models.ForeignKey(Extension, blank=True, null=True)
    total_calls = models.IntegerField()
    total_seconds = models.IntegerField()
    cost = models.FloatField()
    date = models.DateField()

class UserDestinationDetail(models.Model):
    extension = models.ForeignKey(Extension, blank=True, null=True)
    total_calls = models.IntegerField()
    total_seconds = models.IntegerField()
    cost = models.FloatField()
    destination_group = models.ForeignKey(DestinationGroup, blank=True, null=True)
    date = models.DateField()

class UserDestinationNumberDetail(models.Model):
    extension = models.ForeignKey(Extension, blank=True, null=True)
    total_calls = models.IntegerField()
    total_seconds = models.IntegerField()
    cost = models.FloatField()
    prefix = models.CharField(max_length = 255)
    number = models.CharField(max_length = 255)
    date = models.DateField()

class ProviderDailyDetail(models.Model):
    provider = models.ForeignKey(Provider, blank=True, null=True)
    cost = models.FloatField()
    total_calls = models.IntegerField()
    total_seconds = models.IntegerField()
    date = models.DateField()

class ProviderDestinationDetail(models.Model):
    provider = models.ForeignKey(Provider, blank=True, null=True)
    cost = models.FloatField()
    total_calls = models.IntegerField()
    total_seconds = models.IntegerField()
    destination_group = models.ForeignKey(DestinationGroup, blank=True, null=True)
    date = models.DateField()

class PinsetDailyDetail(models.Model):
    pinset = models.ForeignKey(Pinset, blank=True, null=True)
    total_calls = models.IntegerField()
    total_seconds = models.IntegerField()
    cost = models.FloatField()
    date = models.DateField()

class PinsetDestinationDetail(models.Model):
    pinset = models.ForeignKey(Pinset, blank=True, null=True)
    total_calls = models.IntegerField()
    total_seconds = models.IntegerField()
    cost = models.FloatField()
    destination_group = models.ForeignKey(DestinationGroup, blank=True, null=True)
    date = models.DateField()

class PinsetDestinationNumberDetail(models.Model):
    pinset = models.ForeignKey(Pinset, blank=True, null=True)
    total_calls = models.IntegerField()
    total_seconds = models.IntegerField()
    cost = models.FloatField()
    prefix = models.CharField(max_length = 255)
    number = models.CharField(max_length = 255)
    date = models.DateField()

class UserInformation(models.Model):
    first_time_user = models.BooleanField(default=True)
    first_import_started = models.DateTimeField(blank=True, null=True)
    is_first_import_finished = models.BooleanField(default=False)
    test_run_in_progress = models.BooleanField(default=False)
    processing_in_progress = models.BooleanField(default=False)
    trunks_configured = models.BooleanField(default=False)
    base_tariffs_configured = models.BooleanField(default=False)
    bundles_configured = models.BooleanField(default=False)
    country = CountryField(max_length = 6)
    bussiness_name = models.CharField(max_length=255)
    contact_first_name = models.CharField(max_length=255)
    contact_last_name = models.CharField(max_length=255)
    notification_email = models.CharField(max_length=255)
    currency_code = models.CharField(max_length=20)
    currency_symbol = models.CharField(max_length=10)
    accepted_privacy_policy = models.BooleanField(default=False)

class UnconfiguredCall(models.Model):
    dialed_number = models.CharField(max_length = 255)
    extension_number = models.CharField(max_length = 255)
    pinset_number = models.CharField(max_length = 255)
    asterisk_unique_id = models.CharField(max_length = 255)
    duration = models.IntegerField()
    provider = models.CharField(max_length = 255)
    date = models.DateTimeField()

class ImportResults(models.Model):
    calls_saved = models.IntegerField()
    calls_not_saved = models.IntegerField()

class CDRFilter(models.Model):
    comparison = models.CharField(max_length=10)
    field_name = models.CharField(max_length=50)
    value = models.CharField(max_length=255)
    extras = models.CharField(max_length=10, null=True, blank=True)

mango-analytics/tarificador/tarifica/views/bundles.py
#Views for bundles

from django.utils.timezone import utc
import datetime
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from tarifica import forms
from tarifica.tools.asteriskMySQLManager import AsteriskMySQLManager
from tarifica.models import *
from dateutil.relativedelta import *

#@elastix_user_is_authorized()
def createBundle(request, destination_group_id):
    user_info = get_object_or_404(UserInformation, id = 1)
    destination_group = get_object_or_404(DestinationGroup, id=destination_group_id)
    provider = destination_group.provider
    start_date = datetime.datetime.now()
    start_date = datetime.datetime(year=start_date.year, month=start_date.month, day=provider.period_end)
    end_date = start_date + relativedelta(years=2)
    if request.method == 'POST': # If the form has been submitted...
        form = forms.createBundle(request.POST) # A form bound to the POST data
        if form.is_valid(): # All validation rules pass
            name = form.cleaned_data['name']
            tariff_mode = TariffMode.objects.get(id=form.cleaned_data['tariff_mode'])
            cost = form.cleaned_data['cost']
            amount = form.cleaned_data['amount']
            start_date = form.cleaned_data['start_date']
            end_date = form.cleaned_data['end_date']
            priority = form.cleaned_data['priority']
            destination_group.has_bundles=True
            destination_group.save()
            b = Bundle(
                priority = priority,
                name=name,
                destination_group=destination_group,
                tariff_mode=tariff_mode,
                cost=cost,
                amount=amount,
                start_date=start_date,
                end_date=end_date
                )
            b.save()
            return HttpResponseRedirect('/setup') # Redirect after POST
    else:
        form = forms.createBundle(initial={
            'start_date': start_date,
            'end_date': end_date
        }) # An unbound form

    return render(request, 'tarifica/bundles/bundleCreate.html', {
        'start_date': start_date,
        'end_date': end_date,
        'form': form,
        'destination_group': destination_group,
        'user_info': user_info
    })

#@elastix_user_is_authorized()
def updateBundle(request, bundle_id):
    user_info = get_object_or_404(UserInformation, id = 1)
    b = get_object_or_404(Bundle, id = bundle_id)
    if request.method == 'POST': # If the form has been submitted...
        form = forms.updateBundle(request.POST) # A form bound to the POST data
        if form.is_valid(): # All validation rules pass
            b.name = form.cleaned_data['name']
            b.tariff_mode = TariffMode.objects.get(id=form.cleaned_data['tariff_mode'])
            b.cost = form.cleaned_data['cost']
            b.amount = form.cleaned_data['amount']
            b.priority = form.cleaned_data['priority']
            b.save()
            return HttpResponseRedirect('/setup') # Redirect after POST
    else:
        form = forms.updateBundle(initial=
        {'name': b.name,
         'destination_group': b.destination_group,
         'tariff_mode': b.tariff_mode,
         'cost': b.cost,
         'amount': b.amount,
         'priority': b.priority,
        }) # An unbound form

    return render(request, 'tarifica/bundles/bundleUpdate.html', {
        'form': form,
        'bundle' : b,
        'user_info': user_info
    })

#@elastix_user_is_authorized()
def deleteBundle(request, bundle_id):
    bundle = get_object_or_404(Bundle, id = bundle_id)
    destination_group = bundle.destination_group
    bundle.delete()
    if len(Bundle.objects.filter(destination_group = destination_group)) == 0:
        destination_group.has_bundles = False
        destination_group.save()

    return HttpResponseRedirect('/setup')

mango-analytics/tarificador/tarifica/templates/tarifica/providers/providerCreate.html
{% extends "setup.html" %}

{% block title %}Add provider information{% endblock %}

{% block page-title %}
<li>
    <a href="#" style="padding-left: 0px;padding-right: 0px; font-size: 16px;">
        <span class="fui-arrow-right"></span>
    </a>
</li>
<li>
    <a style="margin-left: 10px; text-align:vertical; padding-left: 10px;" href="#">
        Adding information for provider {{provider.asterisk_name}}
    </a>
</li>
{% endblock %}

{% block content %}
<div class="well well-small">
    <form action="{% url 'tarifica:providers_create' provider.asterisk_id %}" method="post" class="form-horizontal">{% csrf_token %}
        {{ form.non_field_errors }}
        <div class="control-group">
            {{ form.name.errors }}
            <label class="control-label" for="id_name">Alias
                <a class="help" href="#" data-toggle="popover" data-original-title="Trunk Alias" data-content="Custom, friendly name for this trunk. Only used within Mango Analytics.">
                    <i class="icon-question-sign"></i>
                </a>
            </label>
            <div class="controls">
                {{ form.name }}
            </div>
        </div>
        <div class="control-group">
            {{ form.monthly_cost.errors }}
            <label class="control-label" for="id_monthly_cost">Monthly Fee
                <a class="help" href="#" data-toggle="popover" data-original-title="Monthly Fee" data-content="Monthly fee charged by this trunk's providers.">
                    <i class="icon-question-sign"></i>
                </a>
            </label>
            <div class="controls">
                {{ form.monthly_cost }}
            </div>
        </div>
        <div class="control-group">
            {{ form.period_end.errors }}
            <label class="control-label" for="id_period_end">Billing start date
                <a class="help" href="#" data-toggle="popover" data-original-title="Billing start date" data-content="Day of the month when billing starts.">
                    <i class="icon-question-sign"></i>
                </a>
            </label>
            <div class="controls">
                {{ form.period_end }}
            </div>
        </div>
        <div class="control-group">
            {{ form.payment_type.errors }}
            <label class="control-label" for="id_payment_type">Payment Method
                <a class="help" href="#" data-toggle="popover" data-original-title="Payment Method" data-content="Do your provider charges you when your billing period ends, or do you need to pay beforehand in order to use their service?">
                    <i class="icon-question-sign"></i>
                </a>
            </label>
            <div class="controls">
                {{ form.payment_type }}
            </div>
        </div>
        <div class="control-group">
            {{ form.channels.errors }}
            <label class="control-label" for="id_channels">Channels
                <a class="help" href="#" data-toggle="popover" data-original-title="Channel Number" data-content="How many calls can you make at the same time?">
                    <i class="icon-question-sign"></i>
                </a>
            </label>
            <div class="controls">
                {{ form.channels }}
            </div>
        </div>
        <div class="form-actions">
            <button type="submit" class="btn btn-primary">Save Changes</button>
            <a class="btn" href="{% url 'tarifica:setup' %}">Cancel</a>
        </div>
    </form>
</div>

{% endblock %}

{% block js %}
    {{ block.super }}
    <script type="text/javascript">
    $(function() {
        $('a.help').each(function(){
            $(this).popover({
                html: true,
                trigger: 'hover'
            });
        });
    });
    </script>
{% endblock %}

mango-analytics/tarificador/tarifica/templates/tarifica/providers/providerGet.html
{% extends "setup.html" %}

{% block title %}Provider {{ provider.name }}{% endblock %}

{% block page-title %}
<li>
    <a href="#" style="padding-left: 0px;padding-right: 0px; font-size: 16px;">
        <span class="fui-arrow-right"></span>
    </a>
</li>
<li>
    <a style="margin-left: 10px; text-align:vertical; padding-left: 10px;" href="#">
        Provider {{ provider.name }} detail
    </a>
</li>
{% endblock %}

{% block content %}
<div class="row-fluid well well-small">
    <div class="span6">
        <p>
            Asterisk Channel Id: <strong>{{ provider.asterisk_channel_id }}</strong>
        </p>
        <p>
            Asterisk Name: <strong>{{ provider.asterisk_name }}</strong>
        </p>
        <p>
            Tech: <strong>{{ provider.provider_tech | upper }}</strong>
        </p>
        <p>
            Channels: <strong>{{ provider.channels }}</strong>
        </p>
    </div>
    <div class="span6">
        <p>
            Monthly Cost: <strong>{{ user_info.currency_symbol }}{{ provider.monthly_cost }} {{ user_info.currency_code }}</strong>
        </p>
        <p>
            Payment Type: <strong>{{ provider.payment_type }}</strong>
        </p>
        <p>
            Billing Period End: <strong>{{ provider.period_end }}</strong>
        </p>
    </div>
</div>

<div class="well well-small">
    <h4 style="display:inline-block">Rates</h4>
    <span class="pull-right">
        <a href="{% url 'tarifica:destinations_create' provider.id %}" class="btn btn-primary">Add Base Rates</a>
    </span>
    <table class="table table-striped table-hovered table-condensed">
        <thead>
            <tr>
                <th>Name</th>
                <th>Country</th>
                <th>Prefix</th>
                <th>Minute Fee</th>
                <th>Connection Fee</th>
                <th>Billing Interval</th>
            </tr>
        </thead>
        <tbody>
            {% for dest in destination_groups %}
            <tr>
                <td>{{ dest.destination_name.name }}</td>
                <td>
                    <img src="{{ dest.destination_country.flag }}">
                    {{ dest.destination_country.name }}
                </td>
                <td>{{ dest.prefix }}</td>
                <td>{{ user_info.currency_symbol }}{{ dest.minute_fee }} {{ user_info.currency_code }}</td>
                <td>{{ user_info.currency_symbol }}{{ dest.connection_fee|floatformat:2 }} {{ user_info.currency_code }}</td>
                <td>{{ dest.billing_interval }}</td>
                <td>
                    <a href="{% url 'tarifica:bundles_create' dest.id %}">
                        Assign Bundles
                    </a>
                </td>
                <td>
                    <a href="{% url 'tarifica:destinations_update' dest.id %}" class="btn btn-mini btn-info" data-toggle="tooltip" title="Update">
                        <i class="icon-pencil icon-white"></i>
                    </a>
                    <a href="{% url 'tarifica:destinations_delete' dest.id %}" class="btn btn-mini btn-danger" data-toggle="tooltip" title="Delete">
                        <i class="icon-remove-sign icon-white"></i>
                    </a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<div class="well well-small">
    <!-- Paquetes configurados -->
    <h4>Configured Bundles</h4>
    <table class="table table-striped table-hovered table-condensed">
        <thead>
            <tr>
                <th>Destination</th>
                <th>Cost {{ user_info.currency_code }}</th>
                <th>Minutes/Sessions</th>
                <th>Start</th>
                <th>End</th>
                <th>Used</th>
                <th>Priority</th>
            </tr>
        </thead>
        <tbody>
            {% for bundle in bundles %}
            <tr>
                <td><img src="{{ bundle.destination_group.destination_country.flag }}"> {{ bundle.destination_group.destination_name.name }}</td>
                <td>{{ user_info.currency_symbol }}{{ bundle.cost|floatformat:2 }}</td>
                <td>{{ bundle.amount }} {{ bundle.tariff_mode }}s</td>
                <td>{{ bundle.start_date | date:"d/M/Y" }}</td>
                <td>{{ bundle.end_date | date:"d/M/Y" }}</td>
                <td>{{ bundle.usage }}</td>
                <td>{{ bundle.priority }}</td>
                <td>
                    <a href="{% url 'tarifica:bundles_update' bundle.id %}" class="btn btn-mini btn-info" data-toggle="tooltip" title="Edit">
                        <i class="icon-pencil icon-white"></i>
                    </a>
                    <a href="{% url 'tarifica:bundles_delete' bundle.id %}" class="btn btn-mini btn-danger" data-toggle="tooltip" title="Delete">
                        <i class="icon-remove-sign icon-white"></i></a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

mango-analytics/tarificador/tarifica/templates/tarifica/providers/providerUpdate.html
{% extends "setup.html" %}

{% block title %}Update provider information{% endblock %}

{% block page-title %}
<li>
    <a href="#" style="padding-left: 0px;padding-right: 0px; font-size: 16px;">
        <span class="fui-arrow-right"></span>
    </a>
</li>
<li>
    <a style="margin-left: 10px; text-align:vertical; padding-left: 10px;" href="#">
        Updating provider {{ provider.name }}
    </a>
</li>
{% endblock %}

{% block content %}
<div class="well well-small">
    <form action="{% url 'tarifica:providers_update' provider.id %}" method="post" class="form-horizontal">{% csrf_token %}
        {{ form.non_field_errors }}
        <div class="control-group">
            {{ form.name.errors }}
            <label class="control-label" for="id_name">Name</label>
            <div class="controls">
                {{ form.name }}
                <span class="help-inline">Custom name for this trunk.</span>
            </div>
        </div>
        <div class="control-group">
            {{ form.monthly_cost.errors }}
            <label class="control-label" for="id_monthly_cost">Monthly Fee</label>
            <div class="controls">
                {{ form.monthly_cost }}
                <span class="help-inline">Monthly fee charged by this trunk's providers.</span>
            </div>
        </div>
        <div class="control-group">
            {{ form.period_end.errors }}
            <label class="control-label" for="id_period_end">Billing start date</label>
            <div class="controls">
                {{ form.period_end }}
                <span class="help-inline">Day of the month when billing starts.</span>
            </div>
        </div>
        <div class="control-group">
            {{ form.payment_type.errors }}
            <label class="control-label" for="id_payment_type">Payment Method</label>
            <div class="controls">
                {{ form.payment_type }}
                <span class="help-inline">Do your provider charges you when your billing period ends, or do you need to pay beforehand in order to use their service?</span>
            </div>
        </div>
        <div class="control-group">
            {{ form.channels.errors }}
            <label class="control-label" for="id_channels">Channels</label>
            <div class="controls">
                {{ form.channels }}
                <span class="help-inline">How many calls can you make at the same time?</span>
            </div>
        </div>
        <div class="form-actions">
            <button type="submit" class="btn btn-primary">Save Changes</button>
            <a class="btn" href="{% url 'tarifica:setup' %}">Cancel</a>
        </div>
    </form>
</div>
{% endblock %}