mango-analytics/tarificador/accounts/urls.py
from django.conf.urls import patterns, url

from accounts import views

urlpatterns = patterns('',
	url(r'login$', views.index, name='login'),
	url(r'login/log$', views.log, name='log'),
	url(r'login/logged/lo$', views.details, name='lo'),
)

mango-analytics/tarificador/tarifica/urls.py
from django.conf.urls import patterns, url
from tarifica.views import bundles, destinationGroups, general, providers, \
   trunks, users, wizard, config, pinsets, cdr, security

urlpatterns = patterns('',
   url(r'^login$', security.login_view, name='login'),
   url(r'^logout$', security.logout_view, name='logout'),

   url(r'^$', general.setup, name = 'setup'),
   url(r'^setup$', general.setup, name = 'setup'),
   url(r'^privacy$', general.privacy, name = 'privacy'),
   url(r'^manual$', general.manual, name = 'manual'),
   
   url(r'^config$', config.config, name = 'config'),
   url(r'^config/update/(?P<option>\w+)$', config.updateUser, name = 'config_update_user'),

   url(r'^providers/create/(?P<asterisk_id>\d+)$', providers.createProvider, name = 'providers_create'),
   url(r'^providers/update/(?P<provider_id>\d+)$', providers.updateProvider, name = 'providers_update'),
   url(r'^providers/delete/(?P<provider_id>\d+)$', providers.deleteProvider, name = 'providers_delete'),
   url(r'^providers/(?P<provider_id>\d+)$', providers.getProvider, name = 'providers_get'),
   
   url(r'^destinations/create/(?P<provider_id>\d+)$', destinationGroups.createDestinationGroup, name = 'destinations_create'),
   url(r'^destinations/update/(?P<destination_group_id>\d+)$', destinationGroups.updateDestinationGroup, name = 'destinations_update'),
   url(r'^destinations/delete/(?P<destination_group_id>\d+)$', destinationGroups.deleteDestinationGroup, name = 'destinations_delete'),
   
   url(r'^bundles/create/(?P<destination_group_id>\d+)$', bundles.createBundle, name = 'bundles_create'),
   url(r'^bundles/update/(?P<bundle_id>\d+)$', bundles.updateBundle, name = 'bundles_update'),
   url(r'^bundles/delete/(?P<bundle_id>\d+)$', bundles.deleteBundle, name = 'bundles_delete'),

   url(r'^trunks$', trunks.general, name = 'trunks'),
   url(r'^trunks/(?P<period_id>\w+)$', trunks.general, name = 'trunks_period'),
   url(r'^trunks/get/(?P<provider_id>\d+)$', trunks.getTrunk, name = 'trunks_get'),
   url(r'^trunks/get/(?P<provider_id>\d+)/(?P<period_id>\w+)$', trunks.getTrunk, name = 'trunks_get_period'),
   url(r'^trunks/download/(?P<provider_id>\d+)/(?P<start_date>[A-Za-z0-9_\-]+)/(?P<end_date>[A-Za-z0-9_\-]+)$', trunks.downloadTrunkCDR, name = 'trunks_download_cdr'),

   url(r'^realtime$', general.realtime, name = 'realtime'),
   url(r'^realtime/(?P<action>\w+)$', general.realtime, name = 'realtime'),

   url(r'^dashboard$', general.dashboard, name = 'dashboard'),
   
   url(r'^cdr$', cdr.general, name = 'cdr'),
   url(r'^cdr/page/(?P<page>\w+)$', cdr.general, name = 'cdr'),

   url(r'^users/general$', users.generalUsers, name = 'users_general'),
   url(r'^users/general/(?P<period_id>\w+)$', users.generalUsers, name = 'users_general_period'),
   url(r'^users/detail/(?P<extension_id>\d+)$', users.detailUsers, name = 'users_detail'),
   url(r'^users/detail/(?P<extension_id>\d+)/(?P<period_id>\w+)$', users.detailUsers, name = 'users_detail_period'),
   url(r'^users/analytics/(?P<extension_id>\d+)$', users.analyticsUsers, name = 'users_analytics'),
   url(r'^users/analytics/(?P<extension_id>\d+)/(?P<period_id>\w+)$', users.analyticsUsers, name = 'users_analytics_period'),

   url(r'^wizard/start$', wizard.start, name = "wizard_start"),
   url(r'^wizard/start/(?P<page>\d+)$', wizard.start, name = "wizard_start"),
   url(r'^wizard/testRun$', wizard.testrun, name = "wizard_test_run"),
   url(r'^wizard/testRun/(?P<default>\w+)$', wizard.testrun, name = "wizard_test_run"),
   url(r'^wizard/checkTestRunStatus$', wizard.checkTestRunStatus, name = "wizard_check_test_run_status"),
   url(r'^wizard/checkTestRunStatus/(?P<action>\w+)$', wizard.checkTestRunStatus, name = "wizard_check_test_run_status"),
   url(r'^wizard/results$', wizard.results, name = "wizard_results"),
   url(r'^wizard/run$', wizard.run, name = "wizard_run"),
   url(r'^wizard/run/(?P<default>\w+)$', wizard.run, name = "wizard_run"),
   url(r'^wizard/checkProcessingStatus$', wizard.checkProcessingStatus, name = "wizard_check_processing_status"),
   url(r'^wizard/checkProcessingStatus/(?P<action>\w+)$', wizard.checkProcessingStatus, name = "wizard_check_processing_status"),

   url(r'^pinsets/general$', pinsets.generalPinsets, name = 'pinsets_general'),
   url(r'^pinsets/general/(?P<period_id>\w+)$', pinsets.generalPinsets, name = 'pinsets_general_period'),
   url(r'^pinsets/detail/(?P<pinset_id>\d+)$',pinsets.detailPinsets, name = 'pinsets_detail'),
   url(r'^pinsets/detail/(?P<pinset_id>\d+)/(?P<period_id>\w+)$', pinsets.detailPinsets, name = 'pinsets_detail_period'),
   url(r'^pinsets/analytics/(?P<pinset_id>\d+)$', pinsets.analyticsPinsets, name = 'pinsets_analytics'),
   url(r'^pinsets/analytics/(?P<pinset_id>\d+)/(?P<period_id>\w+)$', pinsets.analyticsPinsets, name = 'pinsets_analytics_period'),
)

mango-analytics/tarificador/tarificador/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'tarificador.views.home', name='home'),
    # url(r'^tarificador/', include('tarificador.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^accounts/', include('accounts.urls',namespace="accounts")),
    url(r'^', include('tarifica.urls',namespace="tarifica")),
    url(r'^users/', include(admin.site.urls)),
)

mango-analytics/tarificador/tarifica/models.py
from django.db import models
from tarifica.django_countries.fields import CountryField

# Create your models here.
class PaymentType(models.Model):
    name = models.CharField(max_length = 255, default="Pospago")
    def __unicode__(self):
        return self.name

class TariffMode(models.Model):
    name = models.CharField(max_length = 255)
    def __unicode__(self):
        return self.name

class Provider(models.Model):
    asterisk_id = models.IntegerField()
    asterisk_name = models.CharField(max_length = 255)
    asterisk_channel_id = models.CharField(max_length=255)
    name = models.CharField(max_length = 255)
    monthly_cost = models.FloatField(default=0)
    provider_tech = models.CharField(max_length = 50, blank=True)
    payment_type = models.ForeignKey(PaymentType, blank=True, null=True)
    channels = models.IntegerField(blank=True, default=0)
    period_end = models.IntegerField(default=0)
    is_configured = models.BooleanField(default=False)
    def __unicode__(self):
        return self.asterisk_name

class DestinationName(models.Model):
    name = models.CharField(max_length = 255)
    def __unicode__(self):
        return self.name

class DestinationGroup(models.Model):
    provider = models.ForeignKey(Provider, blank=True, null=True)
    prefix = models.CharField(max_length = 255, blank=True, default="")
    notes = models.TextField(null=True, blank=True)
    connection_fee = models.FloatField()
    minute_fee = models.FloatField(default=60)
    billing_interval = models.IntegerField()
    destination_name = models.ForeignKey(DestinationName, blank=True, null=True)
    destination_country = CountryField(max_length = 6)
    has_bundles = models.BooleanField(default=False)
    def __unicode__(self):
        return f'{self.provider.name}-{self.destination_name.name}'

class Bundle(models.Model):
    name = models.CharField(max_length = 255)
    destination_group = models.ForeignKey(DestinationGroup, blank=True, null=True)
    tariff_mode = models.ForeignKey(TariffMode, blank=True, null=True)
    cost = models.FloatField()
    usage = models.IntegerField(blank=True, null=True, default=0)
    virtual_usage = models.IntegerField(blank=True, null=True, default=0)
    amount = models.IntegerField()
    priority = models.IntegerField()
    is_active = models.BooleanField(default=True)
    start_date = models.DateField()
    end_date = models.DateField()

class Call(models.Model):
    dialed_number = models.CharField(max_length = 255)
    extension_number = models.CharField(max_length = 255)
    pinset_number = models.CharField(max_length = 255)
    asterisk_unique_id = models.CharField(max_length = 255)
    duration = models.IntegerField()
    cost = models.FloatField()
    date = models.DateTimeField()
    destination_group = models.ForeignKey(DestinationGroup, blank=True, null=True)
    provider = models.ForeignKey(Provider, blank=True, null=True)

class Pinset(models.Model):
    pinset_number = models.CharField(max_length = 255)

class Extension(models.Model):
    extension_number = models.CharField(max_length = 255)
    name = models.CharField(max_length = 255)

class UserDailyDetail(models.Model):
    extension = models.ForeignKey(Extension, blank=True, null=True)
    total_calls = models.IntegerField()
    total_seconds = models.IntegerField()
    cost = models.FloatField()
    date = models.DateField()

class UserDestinationDetail(models.Model):
    extension = models.ForeignKey(Extension, blank=True, null=True)
    total_calls = models.IntegerField()
    total_seconds = models.IntegerField()
    cost = models.FloatField()
    destination_group = models.ForeignKey(DestinationGroup, blank=True, null=True)
    date = models.DateField()

class UserDestinationNumberDetail(models.Model):
    extension = models.ForeignKey(Extension, blank=True, null=True)
    total_calls = models.IntegerField()
    total_seconds = models.IntegerField()
    cost = models.FloatField()
    prefix = models.CharField(max_length = 255)
    number = models.CharField(max_length = 255)
    date = models.DateField()

class ProviderDailyDetail(models.Model):
    provider = models.ForeignKey(Provider, blank=True, null=True)
    cost = models.FloatField()
    total_calls = models.IntegerField()
    total_seconds = models.IntegerField()
    date = models.DateField()

class ProviderDestinationDetail(models.Model):
    provider = models.ForeignKey(Provider, blank=True, null=True)
    cost = models.FloatField()
    total_calls = models.IntegerField()
    total_seconds = models.IntegerField()
    destination_group = models.ForeignKey(DestinationGroup, blank=True, null=True)
    date = models.DateField()

class PinsetDailyDetail(models.Model):
    pinset = models.ForeignKey(Pinset, blank=True, null=True)
    total_calls = models.IntegerField()
    total_seconds = models.IntegerField()
    cost = models.FloatField()
    date = models.DateField()

class PinsetDestinationDetail(models.Model):
    pinset = models.ForeignKey(Pinset, blank=True, null=True)
    total_calls = models.IntegerField()
    total_seconds = models.IntegerField()
    cost = models.FloatField()
    destination_group = models.ForeignKey(DestinationGroup, blank=True, null=True)
    date = models.DateField()

class PinsetDestinationNumberDetail(models.Model):
    pinset = models.ForeignKey(Pinset, blank=True, null=True)
    total_calls = models.IntegerField()
    total_seconds = models.IntegerField()
    cost = models.FloatField()
    prefix = models.CharField(max_length = 255)
    number = models.CharField(max_length = 255)
    date = models.DateField()

class UserInformation(models.Model):
    first_time_user = models.BooleanField(default=True)
    first_import_started = models.DateTimeField(blank=True, null=True)
    is_first_import_finished = models.BooleanField(default=False)
    test_run_in_progress = models.BooleanField(default=False)
    processing_in_progress = models.BooleanField(default=False)
    trunks_configured = models.BooleanField(default=False)
    base_tariffs_configured = models.BooleanField(default=False)
    bundles_configured = models.BooleanField(default=False)
    country = CountryField(max_length = 6)
    bussiness_name = models.CharField(max_length=255)
    contact_first_name = models.CharField(max_length=255)
    contact_last_name = models.CharField(max_length=255)
    notification_email = models.CharField(max_length=255)
    currency_code = models.CharField(max_length=20)
    currency_symbol = models.CharField(max_length=10)
    accepted_privacy_policy = models.BooleanField(default=False)

class UnconfiguredCall(models.Model):
    dialed_number = models.CharField(max_length = 255)
    extension_number = models.CharField(max_length = 255)
    pinset_number = models.CharField(max_length = 255)
    asterisk_unique_id = models.CharField(max_length = 255)
    duration = models.IntegerField()
    provider = models.CharField(max_length = 255)
    date = models.DateTimeField()

class ImportResults(models.Model):
    calls_saved = models.IntegerField()
    calls_not_saved = models.IntegerField()

class CDRFilter(models.Model):
    comparison = models.CharField(max_length=10)
    field_name = models.CharField(max_length=50)
    value = models.CharField(max_length=255)
    extras = models.CharField(max_length=10, null=True, blank=True)

mango-analytics/tarificador/tarifica/views/bundles.py
#Views for bundles

from django.utils.timezone import utc
import datetime
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from tarifica import forms
from tarifica.tools.asteriskMySQLManager import AsteriskMySQLManager
from tarifica.models import *
from dateutil.relativedelta import *

#@elastix_user_is_authorized()
def createBundle(request, destination_group_id):
    user_info = get_object_or_404(UserInformation, id = 1)
    destination_group = get_object_or_404(DestinationGroup, id=destination_group_id)
    provider = destination_group.provider
    start_date = datetime.datetime.now()
    start_date = datetime.datetime(year=start_date.year, month=start_date.month, day=provider.period_end)
    end_date = start_date + relativedelta(years=2)
    if request.method == 'POST': # If the form has been submitted...
        form = forms.createBundle(request.POST) # A form bound to the POST data
        if form.is_valid(): # All validation rules pass
            name = form.cleaned_data['name']
            tariff_mode = TariffMode.objects.get(id=form.cleaned_data['tariff_mode'])
            cost = form.cleaned_data['cost']
            amount = form.cleaned_data['amount']
            start_date = form.cleaned_data['start_date']
            end_date = form.cleaned_data['end_date']
            priority = form.cleaned_data['priority']
            destination_group.has_bundles=True
            destination_group.save()
            b = Bundle(
                priority = priority,
                name=name,
                destination_group=destination_group,
                tariff_mode=tariff_mode,
                cost=cost,
                amount=amount,
                start_date=start_date,
                end_date=end_date
                )
            b.save()
            return HttpResponseRedirect('/setup') # Redirect after POST
    else:
        form = forms.createBundle(initial={
            'start_date': start_date,
            'end_date': end_date
        }) # An unbound form

    return render(request, 'tarifica/bundles/bundleCreate.html', {
        'start_date': start_date,
        'end_date': end_date,
        'form': form,
        'destination_group': destination_group,
        'user_info': user_info
    })

#@elastix_user_is_authorized()
def updateBundle(request, bundle_id):
    user_info = get_object_or_404(UserInformation, id = 1)
    b = get_object_or_404(Bundle, id = bundle_id)
    if request.method == 'POST': # If the form has been submitted...
        form = forms.updateBundle(request.POST) # A form bound to the POST data
        if form.is_valid(): # All validation rules pass
            b.name = form.cleaned_data['name']
            b.tariff_mode = TariffMode.objects.get(id=form.cleaned_data['tariff_mode'])
            b.cost = form.cleaned_data['cost']
            b.amount = form.cleaned_data['amount']
            b.priority = form.cleaned_data['priority']
            b.save()
            return HttpResponseRedirect('/setup') # Redirect after POST
    else:
        form = forms.updateBundle(initial=
        {'name': b.name,
         'destination_group': b.destination_group,
         'tariff_mode': b.tariff_mode,
         'cost': b.cost,
         'amount': b.amount,
         'priority': b.priority,
        }) # An unbound form

    return render(request, 'tarifica/bundles/bundleUpdate.html', {
        'form': form,
        'bundle' : b,
        'user_info': user_info
    })

#@elastix_user_is_authorized()
def deleteBundle(request, bundle_id):
    bundle = get_object_or_404(Bundle, id = bundle_id)
    destination_group = bundle.destination_group
    bundle.delete()
    if len(Bundle.objects.filter(destination_group = destination_group)) == 0:
        destination_group.has_bundles = False
        destination_group.save()

    return HttpResponseRedirect('/setup')

mango-analytics/tarificador/tarifica/templates/tarifica/destinationGroups/destinationGroupCreate.html
{% extends "setup.html" %}

{% block title %}Add rate to {{provider.name}}{% endblock %}

{% block page-title %}
<li>
    <a href="#" style="padding-left: 0px;padding-right: 0px; font-size: 16px;">
        <span class="fui-arrow-right"></span>
    </a>
</li>
<li>
    <a style="margin-left: 10px; text-align:vertical; padding-left: 10px;" href="#">
        Add base rate to provider {{provider.name}}
    </a>
</li>
{% endblock %}

{% block content %}

<div class="row-fluid">
    <div class="span6">
        <div class="well well-small">
            <form action="{% url 'tarifica:destinations_create' provider.id %}" method="post" class="form-horizontal">{% csrf_token %}
                {{ form.non_field_errors }}
                <div class="control-group">
                    {{ form.destination_name.errors }}
                    <label class="control-label" for="id_destination_group">Destination
                        <a class="help" href="#" data-toggle="popover" data-original-title="Destination Selection" data-content='Select a destination group for quick future reference for this tariff.'>
                            <i class="icon-question-sign"></i>
                        </a>
                    </label>
                    <div class="controls">
                        {{ form.destination_name }}
                    </div>
                </div>
                <div class="control-group">
                    {{ form.destination_country.errors }}
                    <label class="control-label" for="id_destination_group">Country
                        <a class="help" href="#" data-toggle="popover" data-original-title="Destination Country" data-content="Select a country for us to know where this tariff applies to.">
                            <i class="icon-question-sign"></i>
                        </a>
                    </label>
                    <div class="controls">
                        {{ form.destination_country }}
                    </div>
                </div>
                <div class="control-group">
                    {{ form.prefix.errors }}
                    {{ form.provider.errors }}
                    <label class="control-label" for="id_prefix">Call Prefix
                        <a class="help" href="#" data-toggle="popover" data-original-title="Call Prefix" data-content="The part of the dialed number which indicates where you're calling. It begins with a country code and (in most places) continues with an area code. It also changes according to your provider. If you're unsure of how you're calling, you can check it by accessing your Elastix call history.<br><hr>If you want to add a <strong>Default Tariff</strong>, that is, a cost that should be applied if the prefix doesn't fit into any other configured tariffs, leave this space blank.">
                            <i class="icon-question-sign"></i>
                        </a>
                    </label>
                    <div class="controls">
                        {{ form.prefix }}
                    </div>
                </div>
                <div class="control-group">
                    {{ form.minute_fee.errors }}
                    <label class="control-label" for="id_minute_fee">Minute Fee
                        <a class="help" href="#" data-toggle="popover" data-original-title="Minute Fee" data-content="If your provider bills your per minute or per fraction of a minute, input the minute fee. If your provider bills you by fractions of a minute, Mango Analytics will adjust the rate accordingly.">
                            <i class="icon-question-sign"></i>
                        </a>
                    </label>
                    <div class="controls">
                        <div class="input-prepend input-append">
                            <span class="add-on">{{ user_info.currency_symbol }}</span>
                            {{ form.minute_fee }}
                            <span class="add-on">{{ user_info.currency_code }}</span>
                        </div>
                    </div>
                </div>
                <div class="control-group">
                    {{ form.billing_interval.errors }}
                    <label class="control-label" for="id_billing_interval">Billing interval
                        <a class="help" href="#" data-toggle="popover" data-original-title="Billing Interval" data-content="Billing intervals in seconds. If your provider bills you by minute, input '60' here. If your provider bills you by second, input '1'. If your provider bills you by 'x' seconds at a time, input 'x'.">
                            <i class="icon-question-sign"></i>
                        </a>
                    </label>
                    <div class="controls">
                        <div class="input-append">
                            {{ form.billing_interval }}
                            <span class="add-on">seconds</span>
                        </div>
                    </div>
                </div>
                <div class="control-group">
                    {{ form.connection_fee.errors }}
                    <label class="control-label" for="id_connection_fee">Call Connection Fee
                        <a class="help" href="#" data-toggle="popover" data-original-title="Call Connection Fee" data-content="If your provider bills you all calls to this prefix by the number of calls, not minutes, or if they bill you a call connection fee plus a minute fee, input the fee per call here.">
                            <i class="icon-question-sign"></i>
                        </a>
                    </label>
                    <div class="controls">
                        <div class="input-prepend input-append">
                            <span class="add-on">{{ user_info.currency_symbol }}</span>
                            {{ form.connection_fee }}
                            <span class="add-on">{{ user_info.currency_code }}</span>
                        </div>
                    </div>
                </div>
                <div class="control-group">
                    {{ form.notes.errors }}
                    <label class="control-label" for="id_notes">Notes</label>
                    <div class="controls">
                        {{ form.notes }}
                    </div>
                </div>
                {{ form.provider }}
                {{ form.destination_group_id }}
                <div class="form-actions">
                    <button type="submit" class="btn btn-primary">Save Rate</button>
                    <a class="btn" href="{% url 'tarifica:setup' %}">Cancel</a>
                </div>
            </form>
        </div>
    </div>

    <div class="span6 well well-small">
        <div class="row-fluid">
            <div class="span8">
                <h4>Rates configured</h4>
            </div>
            <div class="span4">
                <span class="pull-right">
                <a href="{% url 'tarifica:setup' %}" class="btn btn-primary" style="margin-top:5px;">
                    Return to setup
                </a></span>
            </div>
        </div>

        <hr style="margin: 10px 0;">
        <table class="table table-striped table-condensed table-hovered">
            <thead>
                <tr>
                    <th>Destination</th>
                    <th>Prefix</th>
                    <th>Connection Fee</th>
                    <th>Minute Fee</th>
                </tr>
            </thead>
            <tbody>
                {% for dest in destinations %}
                <tr>
                    <td>
                        <img src="{{ dest.destination_country.flag }}">
                        {{ dest.destination_name.name }}
                    </td>
                    <td>
                        {% if dest.prefix = "" %}
                            Default
                        {% else %}
                            {{ dest.prefix }}
                        {% endif %}
                    </td>
                    <td>{{ user_info.currency_symbol }}{{ dest.connection_fee }} {{ user_info.currency_code }}</td>
                    <td>{{ user_info.currency_symbol }}{{ dest.minute_fee }} {{ user_info.currency_code }}</td>
                    <td>
                        <a href="{% url 'tarifica:destinations_update' dest.id %}" class="btn btn-mini btn-info" data-toggle="tooltip" title="Edit">
                            <i class="icon-pencil icon-white"></i>
                        </a>
                        <a href="{% url 'tarifica:destinations_delete' dest.id %}" class="btn btn-mini btn-danger" data-toggle="tooltip" title="Edit">
                            <i class="icon-remove icon-white"></i>
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

{% block js %}
    {{ block.super }}
    <script type="text/javascript">
    $(function() {
        $('a.help').each(function(){
            $(this).popover({
                html: true,
                trigger: 'hover'
            });
        });
    });
    </script>
{% endblock %}