mango-analytics/tarificador/accounts/urls.py
from django.conf.urls import patterns, url

from accounts import views

urlpatterns = patterns('',
	url(r'login$', views.index, name='login'),
	url(r'login/log$', views.log, name='log'),
	url(r'login/logged/lo$', views.details, name='lo'),
)

mango-analytics/tarificador/tarifica/urls.py
from django.conf.urls import patterns, url
from tarifica.views import bundles, destinationGroups, general, providers, \
   trunks, users, wizard, config, pinsets, cdr, security

urlpatterns = patterns('',
   url(r'^login$', security.login_view, name='login'),
   url(r'^logout$', security.logout_view, name='logout'),

   url(r'^$', general.setup, name = 'setup'),
   url(r'^setup$', general.setup, name = 'setup'),
   url(r'^privacy$', general.privacy, name = 'privacy'),
   url(r'^manual$', general.manual, name = 'manual'),
   
   url(r'^config$', config.config, name = 'config'),
   url(r'^config/update/(?P<option>\w+)$', config.updateUser, name = 'config_update_user'),

   url(r'^providers/create/(?P<asterisk_id>\d+)$', providers.createProvider, name = 'providers_create'),
   url(r'^providers/update/(?P<provider_id>\d+)$', providers.updateProvider, name = 'providers_update'),
   url(r'^providers/delete/(?P<provider_id>\d+)$', providers.deleteProvider, name = 'providers_delete'),
   url(r'^providers/(?P<provider_id>\d+)$', providers.getProvider, name = 'providers_get'),
   
   url(r'^destinations/create/(?P<provider_id>\d+)$', destinationGroups.createDestinationGroup, name = 'destinations_create'),
   url(r'^destinations/update/(?P<destination_group_id>\d+)$', destinationGroups.updateDestinationGroup, name = 'destinations_update'),
   url(r'^destinations/delete/(?P<destination_group_id>\d+)$', destinationGroups.deleteDestinationGroup, name = 'destinations_delete'),
   
   url(r'^bundles/create/(?P<destination_group_id>\d+)$', bundles.createBundle, name = 'bundles_create'),
   url(r'^bundles/update/(?P<bundle_id>\d+)$', bundles.updateBundle, name = 'bundles_update'),
   url(r'^bundles/delete/(?P<bundle_id>\d+)$', bundles.deleteBundle, name = 'bundles_delete'),

   url(r'^trunks$', trunks.general, name = 'trunks'),
   url(r'^trunks/(?P<period_id>\w+)$', trunks.general, name = 'trunks_period'),
   url(r'^trunks/get/(?P<provider_id>\d+)$', trunks.getTrunk, name = 'trunks_get'),
   url(r'^trunks/get/(?P<provider_id>\d+)/(?P<period_id>\w+)$', trunks.getTrunk, name = 'trunks_get_period'),
   url(r'^trunks/download/(?P<provider_id>\d+)/(?P<start_date>[A-Za-z0-9_\-]+)/(?P<end_date>[A-Za-z0-9_\-]+)$', trunks.downloadTrunkCDR, name = 'trunks_download_cdr'),

   url(r'^realtime$', general.realtime, name = 'realtime'),
   url(r'^realtime/(?P<action>\w+)$', general.realtime, name = 'realtime'),

   url(r'^dashboard$', general.dashboard, name = 'dashboard'),
   
   url(r'^cdr$', cdr.general, name = 'cdr'),
   url(r'^cdr/page/(?P<page>\w+)$', cdr.general, name = 'cdr'),

   url(r'^users/general$', users.generalUsers, name = 'users_general'),
   url(r'^users/general/(?P<period_id>\w+)$', users.generalUsers, name = 'users_general_period'),
   url(r'^users/detail/(?P<extension_id>\d+)$', users.detailUsers, name = 'users_detail'),
   url(r'^users/detail/(?P<extension_id>\d+)/(?P<period_id>\w+)$', users.detailUsers, name = 'users_detail_period'),
   url(r'^users/analytics/(?P<extension_id>\d+)$', users.analyticsUsers, name = 'users_analytics'),
   url(r'^users/analytics/(?P<extension_id>\d+)/(?P<period_id>\w+)$', users.analyticsUsers, name = 'users_analytics_period'),

   url(r'^wizard/start$', wizard.start, name = "wizard_start"),
   url(r'^wizard/start/(?P<page>\d+)$', wizard.start, name = "wizard_start"),
   url(r'^wizard/testRun$', wizard.testrun, name = "wizard_test_run"),
   url(r'^wizard/testRun/(?P<default>\w+)$', wizard.testrun, name = "wizard_test_run"),
   url(r'^wizard/checkTestRunStatus$', wizard.checkTestRunStatus, name = "wizard_check_test_run_status"),
   url(r'^wizard/checkTestRunStatus/(?P<action>\w+)$', wizard.checkTestRunStatus, name = "wizard_check_test_run_status"),
   url(r'^wizard/results$', wizard.results, name = "wizard_results"),
   url(r'^wizard/run$', wizard.run, name = "wizard_run"),
   url(r'^wizard/run/(?P<default>\w+)$', wizard.run, name = "wizard_run"),
   url(r'^wizard/checkProcessingStatus$', wizard.checkProcessingStatus, name = "wizard_check_processing_status"),
   url(r'^wizard/checkProcessingStatus/(?P<action>\w+)$', wizard.checkProcessingStatus, name = "wizard_check_processing_status"),

   url(r'^pinsets/general$', pinsets.generalPinsets, name = 'pinsets_general'),
   url(r'^pinsets/general/(?P<period_id>\w+)$', pinsets.generalPinsets, name = 'pinsets_general_period'),
   url(r'^pinsets/detail/(?P<pinset_id>\d+)$',pinsets.detailPinsets, name = 'pinsets_detail'),
   url(r'^pinsets/detail/(?P<pinset_id>\d+)/(?P<period_id>\w+)$', pinsets.detailPinsets, name = 'pinsets_detail_period'),
   url(r'^pinsets/analytics/(?P<pinset_id>\d+)$', pinsets.analyticsPinsets, name = 'pinsets_analytics'),
   url(r'^pinsets/analytics/(?P<pinset_id>\d+)/(?P<period_id>\w+)$', pinsets.analyticsPinsets, name = 'pinsets_analytics_period'),
)

mango-analytics/tarificador/tarificador/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'tarificador.views.home', name='home'),
    # url(r'^tarificador/', include('tarificador.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^accounts/', include('accounts.urls',namespace="accounts")),
    url(r'^', include('tarifica.urls',namespace="tarifica")),
    url(r'^users/', include(admin.site.urls)),
)

mango-analytics/tarificador/tarifica/views/bundles.py
#Views for bundles

from django.utils.timezone import utc
import datetime
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from tarifica import forms
from tarifica.tools.asteriskMySQLManager import AsteriskMySQLManager
from tarifica.models import *
from dateutil.relativedelta import *

#@elastix_user_is_authorized()
def createBundle(request, destination_group_id):
    user_info = get_object_or_404(UserInformation, id = 1)
    destination_group = get_object_or_404(DestinationGroup, id=destination_group_id)
    provider = destination_group.provider
    start_date = datetime.datetime.now()
    start_date = datetime.datetime(year=start_date.year, month=start_date.month, day=provider.period_end)
    end_date = start_date + relativedelta(years=2)
    if request.method == 'POST': # If the form has been submitted...
        form = forms.createBundle(request.POST) # A form bound to the POST data
        if form.is_valid(): # All validation rules pass
            name = form.cleaned_data['name']
            tariff_mode = TariffMode.objects.get(id=form.cleaned_data['tariff_mode'])
            cost = form.cleaned_data['cost']
            amount = form.cleaned_data['amount']
            start_date = form.cleaned_data['start_date']
            end_date = form.cleaned_data['end_date']
            priority = form.cleaned_data['priority']
            destination_group.has_bundles=True
            destination_group.save()
            b = Bundle(
                priority = priority,
                name=name,
                destination_group=destination_group,
                tariff_mode=tariff_mode,
                cost=cost,
                amount=amount,
                start_date=start_date,
                end_date=end_date
                )
            b.save()
            return HttpResponseRedirect('/setup') # Redirect after POST
    else:
        form = forms.createBundle(initial={
            'start_date': start_date,
            'end_date': end_date
        }) # An unbound form

    return render(request, 'tarifica/bundles/bundleCreate.html', {
        'start_date': start_date,
        'end_date': end_date,
        'form': form,
        'destination_group': destination_group,
        'user_info': user_info
    })

#@elastix_user_is_authorized()
def updateBundle(request, bundle_id):
    user_info = get_object_or_404(UserInformation, id = 1)
    b = get_object_or_404(Bundle, id = bundle_id)
    if request.method == 'POST': # If the form has been submitted...
        form = forms.updateBundle(request.POST) # A form bound to the POST data
        if form.is_valid(): # All validation rules pass
            b.name = form.cleaned_data['name']
            b.tariff_mode = TariffMode.objects.get(id=form.cleaned_data['tariff_mode'])
            b.cost = form.cleaned_data['cost']
            b.amount = form.cleaned_data['amount']
            b.priority = form.cleaned_data['priority']
            b.save()
            return HttpResponseRedirect('/setup') # Redirect after POST
    else:
        form = forms.updateBundle(initial=
        {'name': b.name,
         'destination_group': b.destination_group,
         'tariff_mode': b.tariff_mode,
         'cost': b.cost,
         'amount': b.amount,
         'priority': b.priority,
        }) # An unbound form

    return render(request, 'tarifica/bundles/bundleUpdate.html', {
        'form': form,
        'bundle' : b,
        'user_info': user_info
    })

#@elastix_user_is_authorized()
def deleteBundle(request, bundle_id):
    bundle = get_object_or_404(Bundle, id = bundle_id)
    destination_group = bundle.destination_group
    bundle.delete()
    if len(Bundle.objects.filter(destination_group = destination_group)) == 0:
        destination_group.has_bundles = False
        destination_group.save()

    return HttpResponseRedirect('/setup')

mango-analytics/tarificador/tarifica/views/config.py
#General views

import datetime
from django.utils.timezone import utc
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect, HttpResponse
from tarifica.tools.asteriskMySQLManager import AsteriskMySQLManager
from tarifica.models import *
from tarifica import forms
from django.db import connection, transaction
import json
from django.contrib.auth.decorators import login_required

@login_required(login_url='tarifica:login')
def config(request):
    user_info = UserInformation.objects.get(pk = 1)
    if request.method == 'POST': # If the form has been submitted...
        form = forms.getUserInfo(request.POST)
        if form.is_valid(): # All validation rules pass
            user_info.country = form.cleaned_data['country']
            user_info.bussiness_name = form.cleaned_data['bussiness_name']
            user_info.contact_first_name = form.cleaned_data['contact_first_name']
            user_info.contact_last_name = form.cleaned_data['contact_last_name']
            user_info.notification_email = form.cleaned_data['notification_email']
            user_info.currency_code = form.cleaned_data['currency_code']
            user_info.currency_symbol = form.cleaned_data['currency_symbol']
            user_info.save()
            return HttpResponseRedirect('/dashboard') # Redirect after POST
    else:
        form = forms.getUserInfo(initial={
            'country': user_info.country,
            'bussiness_name': user_info.bussiness_name,
            'contact_first_name': user_info.contact_first_name,
            'contact_last_name': user_info.contact_last_name,
            'notification_email': user_info.notification_email,
            'currency_code': user_info.currency_code,
            'currency_symbol': user_info.currency_symbol,
        })

    return render(request, 'tarifica/config/config.html', {
        'form': form
    })

@login_required(login_url='tarifica:login')
def updateUser(request, option):
    user_info = UserInformation.objects.get(pk = 1)
    if option == "trunks_configured":
        user_info.trunks_configured = True
    elif option == "base_tariffs_configured":
        user_info.base_tariffs_configured = True
    elif option == "bundles_configured":
        user_info.bundles_configured = True

    user_info.save()
    return HttpResponseRedirect('/setup')

mango-analytics/tarificador/tarifica/views/destinationGroups.py
#Views for providers

import datetime
from django.utils.timezone import utc
from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.http import HttpResponseRedirect, HttpResponse
from tarifica import forms
from tarifica.tools.asteriskMySQLManager import AsteriskMySQLManager
from tarifica.models import *
from django.contrib.auth.decorators import login_required

@login_required(login_url='tarifica:login')
def createDestinationGroup(request, provider_id):
    user_info = get_object_or_404(UserInformation, id = 1)
    provider = get_object_or_404(Provider, id = provider_id)
    destinations = DestinationGroup.objects.filter(provider_id = provider_id)
    if request.method == 'POST': # If the form has been submitted...
        form = forms.createDestinationGroup(request.POST) # A form bound to the POST data
        if form.is_valid(): # All validation rules pass
            d = DestinationGroup(
            	provider=provider, 
            	destination_name=DestinationName.objects.get(id=form.cleaned_data['destination_name']), 
            	destination_country=form.cleaned_data['destination_country'], 
                prefix=form.cleaned_data['prefix'], 
            	billing_interval=form.cleaned_data['billing_interval'], 
                minute_fee=form.cleaned_data['minute_fee'],
                connection_fee=form.cleaned_data['connection_fee'],
            	notes=form.cleaned_data['notes'],
            )
            d.save()
            return HttpResponseRedirect(f'/destinations/create/{provider_id}')
    else:
        form = forms.createDestinationGroup(initial=
        {
            'destination_country': user_info.country,
            'minute_fee': 0.00,
            'connection_fee': 0.00,
            'billing_interval': 60,
            'provider': provider.id,
            'destination_group_id': 0,
        }) # An unbound form

    return render(request, 'tarifica/destinationGroups/destinationGroupCreate.html', {
        'form': form,
        'provider' : provider,
        'destinations' : destinations,
        'user_info': user_info
    })

@login_required(login_url='tarifica:login')
def updateDestinationGroup(request, destination_group_id):
    user_info = get_object_or_404(UserInformation, id = 1)
    destination_group = get_object_or_404(DestinationGroup, id = destination_group_id)
    if request.method == 'POST': # If the form has been submitted...
        form = forms.createDestinationGroup(request.POST) # A form bound to the POST data
        if form.is_valid(): # All validation rules pass
            destination_group.destination_name = DestinationName.objects.get(id=form.cleaned_data['destination_name'])
            destination_group.destination_country = form.cleaned_data['destination_country']
            destination_group.prefix = form.cleaned_data['prefix']
            destination_group.minute_fee = form.cleaned_data['minute_fee']
            destination_group.connection_fee = form.cleaned_data['connection_fee']
            destination_group.billing_interval = form.cleaned_data['billing_interval']
            destination_group.notes = form.cleaned_data['notes']
            destination_group.save()
            return HttpResponseRedirect('/setup') # Redirect after POST
    else:
        form = forms.createDestinationGroup(initial={
            'destination_name': destination_group.destination_name,
            'destination_country': destination_group.destination_country,
            'prefix': destination_group.prefix,
            'notes': destination_group.notes,
            'minute_fee': destination_group.minute_fee,
            'connection_fee': destination_group.connection_fee,
            'billing_interval': destination_group.billing_interval,
            'provider': destination_group.provider.id,
            'destination_group_id': destination_group.id
        })

    return render(request, 'tarifica/destinationGroups/destinationGroupUpdate.html', {
        'form': form,
        'destination_group' : destination_group,
        'user_info': user_info
    })

@login_required(login_url='tarifica:login')
def getDestinationGroup(request, provider_id):
    pass

@login_required(login_url='tarifica:login')
def deleteDestinationGroup(request, destination_group_id):
    destination_group = get_object_or_404(DestinationGroup, id = destination_group_id)
    destination_group.delete()
    return HttpResponseRedirect('/setup')

mango-analytics/tarificador/tarifica/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    {% block css %}
        <link href="{% static "tarifica/css/bootstrap.css" %}" rel="stylesheet" media="screen">
        <link href="{% static "tarifica/css/docs.css" %}" rel="stylesheet" media="screen">
        <link href="{% static "tarifica/css/styles.css" %}" rel="stylesheet" media="screen">
    {% endblock %}
    <link rel="shortcut icon" href="images/favicon.ico">
    <title>{% block title %}NEXTOR Tarificador{% endblock %}</title>
    <meta name="viewport" content"width=device-width, initial-scale=1.0">
    <!-- HTML5 shim, for IE6-8 support of HTML5 elements. All other JS at the end of file. -->
    <!--[if lt IE 9]>
      <script src="js/html5shiv.js"></script>
    <![endif]-->
</head>

{% block body %}
{% block body-special %}
<body>
{% endblock %}
    {% block navbar %}
    <div class="navbar">
        <div class="navbar-inner" style="padding-top: 5px; padding-bottom: 5px;">
            <a href="http://www.mangoanalytics.org/" target="_blank">
                <img class="pull-left" src="{% static "tarifica/img/mango_image_.png" %}" alt="Hi!" style="height:40px; margin-right:5px;"/>
            </a>
            <a href="http://www.mangoanalytics.org/" target="_blank">
                <img class="pull-left" src="{% static "tarifica/img/mango_text_logo.png" %}" 
                alt="Hi!" />
            </a>
            {% block localization %}
                <a class="brand" style="margin-left: 10px; text-align:vertical;padding-right: 10px;" href="{% url 'tarifica:dashboard' %}">Dashboard</a>
            {% endblock %}
            <ul class="nav">
                {% block page-title %}
                {% endblock %}
            </ul>
            <ul class="nav pull-right">
                <!-- Data processing status bar-->
                {% if user_info.test_run_in_progress %}
                <li>
                    <a href="{% url 'tarifica:wizard_check_test_run_status' %}"><i class="icon-exclamation-sign"></i> Check Test Run Status</a>
                </li>
                {% endif %}
                {% if user_info.processing_in_progress %}
                <li>
                    <a href="{% url 'tarifica:wizard_check_test_run_status' %}"><i class="icon-exclamation-sign"></i> Check Import Status</a>
                </li>
                {% endif %}
                <li>
                    <a href="{% url 'tarifica:setup' %}"><i class="icon-cog"></i> Setup</a>
                </li>
                <li>
                    <a href="{% url 'tarifica:config' %}"><i class="icon-user"></i> My Settings</a>
                </li>
                <li>
                    <a href="{% url 'tarifica:logout' %}"><i class="icon-off"></i> Logout</a>
                </li>
            </ul>
        </div>
    </div>
    {% endblock %}

    {% block content %}{% endblock %}
    {% block footer %}
    <footer class="well well-small">
        <div class="text-center">
            <ul class="inline">
                <li>
                    <a href="{% url 'tarifica:dashboard' %}">Dashboard</a>
                </li>
                <li>|</li>
                <li>
                    <a href="{% url 'tarifica:config' %}">Settings</a>
                </li>
                <li>|</li>
                <li>
                    <i class="icon-cog"></i> <a href="{% url 'tarifica:setup' %}">Setup</a>
                </li>
                <li>|</li>
                <li>
                    <a href="{% url 'tarifica:manual' %}">Manual</a>
                </li>
                <li>|</li>
                 <li>
                    <i class="icon-question-sign"></i>
                    <a href="#myModal" role="button" data-toggle="modal"> About</a>
                </li>
                <li>|</li>
                <li>
                    <i class="icon-search"></i> <a href="{% url 'tarifica:privacy' %}">Privacy</a>
                </li>
            </ul>
        </div>
        <div>
            <p class="text-center">
                <a target="_blank" href="http://www.mangoanalytics.org">Mango Analytics</a> is licensed under <a target="_blank" href="http://opensource.org/licenses/GPL-3.0">GPLv3</a> by <a target="_blank" href="http://www.nextortelecom.com">NZXT Telecomunicaciones de México, S.A.</a>, 2013
            </p>
            <p class="text-center">
                <strong>Version 1.0.6</strong>
            </p>
        </div>
    </footer>

    <div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h3 id="myModalLabel">About Mango Analytics</h3>
        </div>
        <div class="modal-body">
            <div class="text-center">
                <a target="_blank" href="http://www.mangoanalytics.org">
                    <img src="{% static 'tarifica/img/full_logo.png' %}">
                </a>
            </div>
            <p>
                <a target="_blank" href="http://www.mangoanalytics.org">Mango Analytics</a> is an initiative by Nextor Telecom Mexico (NZXT TELECOMUNICACIONES DE MEXICO SA CV) 
            </p>
            <p>
                Licensed under <a target="_blank" href="http://opensource.org/licenses/GPL-3.0">GPLv3</a>, Version 1.0.6
            </p>
            <p>
                For support and general inquiries, please refer to our website <a target="_blank" href="http://www.mangoanalytics.org">http://www.mangoanalytics.org</a>
            </p>
            <p>
                Please chip in. If you like the software and it helps you lower your phone bills, we would greatly appreciate your contribution, thanks!
            </p>
            <p class="text-center">
                <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_blank" class="text-center">
                    <input type="hidden" name="cmd" value="_s-xclick">
                    <input type="hidden" name="hosted_button_id" value="BFP5VK7VQFZ7L">
                    <input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donate_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
                    <img alt="" border="0" src="https://www.paypalobjects.com/es_XC/i/scr/pixel.gif" width="1" height="1">
                </form>
            </p>
            <img src="http://addon-24.mangoanalytics.org/about.png">
        </div>
        <div class="modal-footer">
            <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
        </div>
    </div>
    {% endblock %}

{% endblock %}

{% block js %}
    <script src="{% static "tarifica/js/jquery.min.js" %}"></script>
    <script src="{% static "tarifica/js/bootstrap.min.js" %}"></script>
{% endblock %}

</body>
</html>

mango-analytics/tarificador/tarifica/templates/config.html
{% extends "base.html"%}

{% block localization %}
    <a class="brand" style="margin-left: 10px; text-align:vertical;" href="{% url 'tarifica:config' %}">My Settings</a>
{% endblock %}

mango-analytics/tarificador/tarifica/templates/pinsets.html
{% extends "base.html" %}

{% block localization %}
    <a class="brand" style="margin-left: 10px; text-align:vertical;" href="{% url 'tarifica:pinsets_general' %}">Pinsets</a>
{% endblock %}

mango-analytics/tarificador/tarifica/templates/setup.html
{% extends "base.html" %}

{% block localization %}
    <a class="brand" style="margin-left: 10px; text-align:vertical;" href="{% url 'tarifica:setup' %}">Setup</a>
{% endblock %}

mango-analytics/tarificador/tarifica/templates/trunks.html
{% extends "base.html"%}

{% block localization %}
    <a class="brand" style="margin-left: 10px; text-align:vertical;" href="{% url 'tarifica:trunks' %}">Trunks</a>
{% endblock %}

mango-analytics/tarificador/tarifica/templates/users.html
{% extends "base.html"%}

{% block localization %}
    <a class="brand" style="margin-left: 10px; text-align:vertical;" href="{% url 'tarifica:users_general' %}">Users</a>
{% endblock %}

mango-analytics/tarificador/tarifica/templates/wizard.html
{% extends "base.html"%}

{% block localization %}
    <a class="brand" style="margin-left: 10px; text-align:vertical;" href="{% url 'tarifica:setup' %}">Wizard</a>
{% endblock %}

{% block js %}
    {{ block.super }}
    <script type="text/javascript">
    $(function() {
        $('a.help').each(function(){
            $(this).popover({
                html: true,
                trigger: 'hover'
            });
        });
    });
    </script>
{% endblock %}