mango-analytics/tarificador/accounts/urls.py
from django.conf.urls import patterns, url

from accounts import views

urlpatterns = patterns('',
	url(r'login$', views.index, name='login'),
	url(r'login/log$', views.log, name='log'),
	url(r'login/logged/lo$', views.details, name='lo'),
)

mango-analytics/tarificador/tarifica/urls.py
from django.conf.urls import patterns, url
from tarifica.views import bundles, destinationGroups, general, providers, \
   trunks, users, wizard, config, pinsets, cdr, security

urlpatterns = patterns('',
   url(r'^login$', security.login_view, name='login'),
   url(r'^logout$', security.logout_view, name='logout'),

   url(r'^$', general.setup, name = 'setup'),
   url(r'^setup$', general.setup, name = 'setup'),
   url(r'^privacy$', general.privacy, name = 'privacy'),
   url(r'^manual$', general.manual, name = 'manual'),
   
   url(r'^config$', config.config, name = 'config'),
   url(r'^config/update/(?P<option>\w+)$', config.updateUser, name = 'config_update_user'),

   url(r'^providers/create/(?P<asterisk_id>\d+)$', providers.createProvider, name = 'providers_create'),
   url(r'^providers/update/(?P<provider_id>\d+)$', providers.updateProvider, name = 'providers_update'),
   url(r'^providers/delete/(?P<provider_id>\d+)$', providers.deleteProvider, name = 'providers_delete'),
   url(r'^providers/(?P<provider_id>\d+)$', providers.getProvider, name = 'providers_get'),
   
   url(r'^destinations/create/(?P<provider_id>\d+)$', destinationGroups.createDestinationGroup, name = 'destinations_create'),
   url(r'^destinations/update/(?P<destination_group_id>\d+)$', destinationGroups.updateDestinationGroup, name = 'destinations_update'),
   url(r'^destinations/delete/(?P<destination_group_id>\d+)$', destinationGroups.deleteDestinationGroup, name = 'destinations_delete'),
   
   url(r'^bundles/create/(?P<destination_group_id>\d+)$', bundles.createBundle, name = 'bundles_create'),
   url(r'^bundles/update/(?P<bundle_id>\d+)$', bundles.updateBundle, name = 'bundles_update'),
   url(r'^bundles/delete/(?P<bundle_id>\d+)$', bundles.deleteBundle, name = 'bundles_delete'),

   url(r'^trunks$', trunks.general, name = 'trunks'),
   url(r'^trunks/(?P<period_id>\w+)$', trunks.general, name = 'trunks_period'),
   url(r'^trunks/get/(?P<provider_id>\d+)$', trunks.getTrunk, name = 'trunks_get'),
   url(r'^trunks/get/(?P<provider_id>\d+)/(?P<period_id>\w+)$', trunks.getTrunk, name = 'trunks_get_period'),
   url(r'^trunks/download/(?P<provider_id>\d+)/(?P<start_date>[A-Za-z0-9_\-]+)/(?P<end_date>[A-Za-z0-9_\-]+)$', trunks.downloadTrunkCDR, name = 'trunks_download_cdr'),

   url(r'^realtime$', general.realtime, name = 'realtime'),
   url(r'^realtime/(?P<action>\w+)$', general.realtime, name = 'realtime'),

   url(r'^dashboard$', general.dashboard, name = 'dashboard'),
   
   url(r'^cdr$', cdr.general, name = 'cdr'),
   url(r'^cdr/page/(?P<page>\w+)$', cdr.general, name = 'cdr'),

   url(r'^users/general$', users.generalUsers, name = 'users_general'),
   url(r'^users/general/(?P<period_id>\w+)$', users.generalUsers, name = 'users_general_period'),
   url(r'^users/detail/(?P<extension_id>\d+)$', users.detailUsers, name = 'users_detail'),
   url(r'^users/detail/(?P<extension_id>\d+)/(?P<period_id>\w+)$', users.detailUsers, name = 'users_detail_period'),
   url(r'^users/analytics/(?P<extension_id>\d+)$', users.analyticsUsers, name = 'users_analytics'),
   url(r'^users/analytics/(?P<extension_id>\d+)/(?P<period_id>\w+)$', users.analyticsUsers, name = 'users_analytics_period'),

   url(r'^wizard/start$', wizard.start, name = "wizard_start"),
   url(r'^wizard/start/(?P<page>\d+)$', wizard.start, name = "wizard_start"),
   url(r'^wizard/testRun$', wizard.testrun, name = "wizard_test_run"),
   url(r'^wizard/testRun/(?P<default>\w+)$', wizard.testrun, name = "wizard_test_run"),
   url(r'^wizard/checkTestRunStatus$', wizard.checkTestRunStatus, name = "wizard_check_test_run_status"),
   url(r'^wizard/checkTestRunStatus/(?P<action>\w+)$', wizard.checkTestRunStatus, name = "wizard_check_test_run_status"),
   url(r'^wizard/results$', wizard.results, name = "wizard_results"),
   url(r'^wizard/run$', wizard.run, name = "wizard_run"),
   url(r'^wizard/run/(?P<default>\w+)$', wizard.run, name = "wizard_run"),
   url(r'^wizard/checkProcessingStatus$', wizard.checkProcessingStatus, name = "wizard_check_processing_status"),
   url(r'^wizard/checkProcessingStatus/(?P<action>\w+)$', wizard.checkProcessingStatus, name = "wizard_check_processing_status"),

   url(r'^pinsets/general$', pinsets.generalPinsets, name = 'pinsets_general'),
   url(r'^pinsets/general/(?P<period_id>\w+)$', pinsets.generalPinsets, name = 'pinsets_general_period'),
   url(r'^pinsets/detail/(?P<pinset_id>\d+)$',pinsets.detailPinsets, name = 'pinsets_detail'),
   url(r'^pinsets/detail/(?P<pinset_id>\d+)/(?P<period_id>\w+)$', pinsets.detailPinsets, name = 'pinsets_detail_period'),
   url(r'^pinsets/analytics/(?P<pinset_id>\d+)$', pinsets.analyticsPinsets, name = 'pinsets_analytics'),
   url(r'^pinsets/analytics/(?P<pinset_id>\d+)/(?P<period_id>\w+)$', pinsets.analyticsPinsets, name = 'pinsets_analytics_period'),
)

mango-analytics/tarificador/tarificador/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'tarificador.views.home', name='home'),
    # url(r'^tarificador/', include('tarificador.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^accounts/', include('accounts.urls',namespace="accounts")),
    url(r'^', include('tarifica.urls',namespace="tarifica")),
    url(r'^users/', include(admin.site.urls)),
)

mango-analytics/tarificador/tarifica/models.py
from django.db import models
from tarifica.django_countries.fields import CountryField

# Create your models here.
class PaymentType(models.Model):
    name = models.CharField(max_length = 255, default="Pospago")
    def __unicode__(self):
        return self.name

class TariffMode(models.Model):
    name = models.CharField(max_length = 255)
    def __unicode__(self):
        return self.name

class Provider(models.Model):
    asterisk_id = models.IntegerField()
    asterisk_name = models.CharField(max_length = 255)
    asterisk_channel_id = models.CharField(max_length=255)
    name = models.CharField(max_length = 255)
    monthly_cost = models.FloatField(default=0)
    provider_tech = models.CharField(max_length = 50, blank=True)
    payment_type = models.ForeignKey(PaymentType, blank=True, null=True)
    channels = models.IntegerField(blank=True, default=0)
    period_end = models.IntegerField(default=0)
    is_configured = models.BooleanField(default=False)
    def __unicode__(self):
        return self.asterisk_name

class DestinationName(models.Model):
    name = models.CharField(max_length = 255)
    def __unicode__(self):
        return self.name

class DestinationGroup(models.Model):
    provider = models.ForeignKey(Provider, blank=True, null=True)
    prefix = models.CharField(max_length = 255, blank=True, default="")
    notes = models.TextField(null=True, blank=True)
    connection_fee = models.FloatField()
    minute_fee = models.FloatField(default=60)
    billing_interval = models.IntegerField()
    destination_name = models.ForeignKey(DestinationName, blank=True, null=True)
    destination_country = CountryField(max_length = 6)
    has_bundles = models.BooleanField(default=False)
    def __unicode__(self):
        return f'{self.provider.name}-{self.destination_name.name}'

class Bundle(models.Model):
    name = models.CharField(max_length = 255)
    destination_group = models.ForeignKey(DestinationGroup, blank=True, null=True)
    tariff_mode = models.ForeignKey(TariffMode, blank=True, null=True)
    cost = models.FloatField()
    usage = models.IntegerField(blank=True, null=True, default=0)
    virtual_usage = models.IntegerField(blank=True, null=True, default=0)
    amount = models.IntegerField()
    priority = models.IntegerField()
    is_active = models.BooleanField(default=True)
    start_date = models.DateField()
    end_date = models.DateField()

class Call(models.Model):
    dialed_number = models.CharField(max_length = 255)
    extension_number = models.CharField(max_length = 255)
    pinset_number = models.CharField(max_length = 255)
    asterisk_unique_id = models.CharField(max_length = 255)
    duration = models.IntegerField()
    cost = models.FloatField()
    date = models.DateTimeField()
    destination_group = models.ForeignKey(DestinationGroup, blank=True, null=True)
    provider = models.ForeignKey(Provider, blank=True, null=True)

class Pinset(models.Model):
    pinset_number = models.CharField(max_length = 255)

class Extension(models.Model):
    extension_number = models.CharField(max_length = 255)
    name = models.CharField(max_length = 255)

class UserDailyDetail(models.Model):
    extension = models.ForeignKey(Extension, blank=True, null=True)
    total_calls = models.IntegerField()
    total_seconds = models.IntegerField()
    cost = models.FloatField()
    date = models.DateField()

class UserDestinationDetail(models.Model):
    extension = models.ForeignKey(Extension, blank=True, null=True)
    total_calls = models.IntegerField()
    total_seconds = models.IntegerField()
    cost = models.FloatField()
    destination_group = models.ForeignKey(DestinationGroup, blank=True, null=True)
    date = models.DateField()

class UserDestinationNumberDetail(models.Model):
    extension = models.ForeignKey(Extension, blank=True, null=True)
    total_calls = models.IntegerField()
    total_seconds = models.IntegerField()
    cost = models.FloatField()
    prefix = models.CharField(max_length = 255)
    number = models.CharField(max_length = 255)
    date = models.DateField()

class ProviderDailyDetail(models.Model):
    provider = models.ForeignKey(Provider, blank=True, null=True)
    cost = models.FloatField()
    total_calls = models.IntegerField()
    total_seconds = models.IntegerField()
    date = models.DateField()

class ProviderDestinationDetail(models.Model):
    provider = models.ForeignKey(Provider, blank=True, null=True)
    cost = models.FloatField()
    total_calls = models.IntegerField()
    total_seconds = models.IntegerField()
    destination_group = models.ForeignKey(DestinationGroup, blank=True, null=True)
    date = models.DateField()

class PinsetDailyDetail(models.Model):
    pinset = models.ForeignKey(Pinset, blank=True, null=True)
    total_calls = models.IntegerField()
    total_seconds = models.IntegerField()
    cost = models.FloatField()
    date = models.DateField()

class PinsetDestinationDetail(models.Model):
    pinset = models.ForeignKey(Pinset, blank=True, null=True)
    total_calls = models.IntegerField()
    total_seconds = models.IntegerField()
    cost = models.FloatField()
    destination_group = models.ForeignKey(DestinationGroup, blank=True, null=True)
    date = models.DateField()

class PinsetDestinationNumberDetail(models.Model):
    pinset = models.ForeignKey(Pinset, blank=True, null=True)
    total_calls = models.IntegerField()
    total_seconds = models.IntegerField()
    cost = models.FloatField()
    prefix = models.CharField(max_length = 255)
    number = models.CharField(max_length = 255)
    date = models.DateField()

class UserInformation(models.Model):
    first_time_user = models.BooleanField(default=True)
    first_import_started = models.DateTimeField(blank=True, null=True)
    is_first_import_finished = models.BooleanField(default=False)
    test_run_in_progress = models.BooleanField(default=False)
    processing_in_progress = models.BooleanField(default=False)
    trunks_configured = models.BooleanField(default=False)
    base_tariffs_configured = models.BooleanField(default=False)
    bundles_configured = models.BooleanField(default=False)
    country = CountryField(max_length = 6)
    bussiness_name = models.CharField(max_length=255)
    contact_first_name = models.CharField(max_length=255)
    contact_last_name = models.CharField(max_length=255)
    notification_email = models.CharField(max_length=255)
    currency_code = models.CharField(max_length=20)
    currency_symbol = models.CharField(max_length=10)
    accepted_privacy_policy = models.BooleanField(default=False)

class UnconfiguredCall(models.Model):
    dialed_number = models.CharField(max_length = 255)
    extension_number = models.CharField(max_length = 255)
    pinset_number = models.CharField(max_length = 255)
    asterisk_unique_id = models.CharField(max_length = 255)
    duration = models.IntegerField()
    provider = models.CharField(max_length = 255)
    date = models.DateTimeField()

class ImportResults(models.Model):
    calls_saved = models.IntegerField()
    calls_not_saved = models.IntegerField()

class CDRFilter(models.Model):
    comparison = models.CharField(max_length=10)
    field_name = models.CharField(max_length=50)
    value = models.CharField(max_length=255)
    extras = models.CharField(max_length=10, null=True, blank=True)

mango-analytics/tarificador/tarifica/views/bundles.py
#Views for bundles

from django.utils.timezone import utc
import datetime
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from tarifica import forms
from tarifica.tools.asteriskMySQLManager import AsteriskMySQLManager
from tarifica.models import *
from dateutil.relativedelta import *

#@elastix_user_is_authorized()
def createBundle(request, destination_group_id):
    user_info = get_object_or_404(UserInformation, id = 1)
    destination_group = get_object_or_404(DestinationGroup, id=destination_group_id)
    provider = destination_group.provider
    start_date = datetime.datetime.now()
    start_date = datetime.datetime(year=start_date.year, month=start_date.month, day=provider.period_end)
    end_date = start_date + relativedelta(years=2)
    if request.method == 'POST': # If the form has been submitted...
        form = forms.createBundle(request.POST) # A form bound to the POST data
        if form.is_valid(): # All validation rules pass
            name = form.cleaned_data['name']
            tariff_mode = TariffMode.objects.get(id=form.cleaned_data['tariff_mode'])
            cost = form.cleaned_data['cost']
            amount = form.cleaned_data['amount']
            start_date = form.cleaned_data['start_date']
            end_date = form.cleaned_data['end_date']
            priority = form.cleaned_data['priority']
            destination_group.has_bundles=True
            destination_group.save()
            b = Bundle(
                priority = priority,
                name=name,
                destination_group=destination_group,
                tariff_mode=tariff_mode,
                cost=cost,
                amount=amount,
                start_date=start_date,
                end_date=end_date
                )
            b.save()
            return HttpResponseRedirect('/setup') # Redirect after POST
    else:
        form = forms.createBundle(initial={
            'start_date': start_date,
            'end_date': end_date
        }) # An unbound form

    return render(request, 'tarifica/bundles/bundleCreate.html', {
        'start_date': start_date,
        'end_date': end_date,
        'form': form,
        'destination_group': destination_group,
        'user_info': user_info
    })

#@elastix_user_is_authorized()
def updateBundle(request, bundle_id):
    user_info = get_object_or_404(UserInformation, id = 1)
    b = get_object_or_404(Bundle, id = bundle_id)
    if request.method == 'POST': # If the form has been submitted...
        form = forms.updateBundle(request.POST) # A form bound to the POST data
        if form.is_valid(): # All validation rules pass
            b.name = form.cleaned_data['name']
            b.tariff_mode = TariffMode.objects.get(id=form.cleaned_data['tariff_mode'])
            b.cost = form.cleaned_data['cost']
            b.amount = form.cleaned_data['amount']
            b.priority = form.cleaned_data['priority']
            b.save()
            return HttpResponseRedirect('/setup') # Redirect after POST
    else:
        form = forms.updateBundle(initial=
        {'name': b.name,
         'destination_group': b.destination_group,
         'tariff_mode': b.tariff_mode,
         'cost': b.cost,
         'amount': b.amount,
         'priority': b.priority,
        }) # An unbound form

    return render(request, 'tarifica/bundles/bundleUpdate.html', {
        'form': form,
        'bundle' : b,
        'user_info': user_info
    })

#@elastix_user_is_authorized()
def deleteBundle(request, bundle_id):
    bundle = get_object_or_404(Bundle, id = bundle_id)
    destination_group = bundle.destination_group
    bundle.delete()
    if len(Bundle.objects.filter(destination_group = destination_group)) == 0:
        destination_group.has_bundles = False
        destination_group.save()

    return HttpResponseRedirect('/setup')

mango-analytics/tarificador/tarifica/templates/tarifica/general/cdr.html
{% extends "base.html" %}
{% load staticfiles %}

{% block css %}
    {{ block.super }}
    <link href="{% static "tarifica/css/bootstrap-datetimepicker.min.css" %}" type="text/css" rel="stylesheet" media="screen">
    <style type="text/css">
    label{
    	display: inline;
    	float:left;
    	margin-right: 5px;
    	font-size: 12px;
    	vertical-align: middle;
    	width: 102px;
    	padding-top: 5px;
    }
    </style>
{% endblock %}

{% block title %} General CDR {% endblock %}

{% block localization %}
    <a class="brand" style="margin-left: 10px; text-align:vertical;padding-right: 10px;" href="{% url 'tarifica:cdr' %}">General CDR</a>
{% endblock %}
            
{% block page-title %}
<li>
    <a href="#" style="padding-left: 0px;padding-right: 0px; font-size: 16px;">
        <span class="fui-arrow-right"></span>
    </a>
</li>
<li>
    <a style="margin-left: 10px; text-align:vertical; padding-left: 10px;" href="#">
        General Cost Detail Report
    </a>
</li>
{% endblock %}

{% block content %}

<div class="well well-small">
	<form action="{% url 'tarifica:cdr' %}" method="post" id="filter-form">{% csrf_token %}
		{% if form.non_field_errors %}
		<div class="alert alert-error">
			<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
			{{ form.non_field_errors }}
		</div>
		{% endif %}
		<div class="row-fluid">
			<div class="span5">
				<div id="datetimepicker1" class="input-append">
                    <label for="id_start_date">Start date</label>
                    {{ form.start_date_comparison }} {{ form.start_date }}
                    <span class="add-on">
                        <i data-time-icon="icon-time" data-date-icon="icon-calendar">
                        </i>
                    </span>
                </div>
                <div id="datetimepicker2" class="input-append">
                    <label for="id_end_date">
                        End date <a class="help" href="#" data-toggle="popover" data-original-title="Want to show calls from one day only?" data-content="Select as start date a day before and as end date a day after the day you want to search.">
                            <i class="icon-question-sign"></i>
                        </a>
                    </label>
                    {{ form.end_date_comparison }} {{ form.end_date }}
                    <span class="add-on">
                        <i data-time-icon="icon-time" data-date-icon="icon-calendar">
                        </i>
                    </span>
                </div>
                <div>
                    <label for="id_dialed_number">Dialed Number</label>
                    {{ form.dialed_number_comparison }} {{ form.dialed_number }}
                </div>
                <div>
                    <label for="id_extension_number">Extension Number</label>
                    {{ form.extension_number_comparison }} {{ form.extension_number }}
                </div>
                <div>
                    <label for="id_pinset_number">Pinset Number</label>
                    {{ form.pinset_number_comparison }} {{ form.pinset_number }}
                </div>
			</div>
			<div class="span5">
				<div>
                    <label for="id_provider">Provider</label>
                    {{ form.provider_comparison }} {{ form.provider }}
                </div>
                <div>
                    <label for="id_destination_group">Destination</label>
                    {{ form.destination_group_comparison }} {{ form.destination_group }}
                </div>
                <div>
                    <label for="id_duration">Duration</label>
                    {{ form.duration_comparison }} {{ form.duration }}
                </div>
                <div>
                    <label for="id_cost">Cost</label>
                    {{ form.cost_comparison }} {{ form.cost }}
                </div>
                <div>
                	{{ form.action }}
                	<button type="submit" id="filter_cdr" class="btn btn-primary">Filter</button>
                </div>
			</div>
			<div class="span2">
                <div>
                    <button class="btn" id="download_cdr">
                    <i class="icon-download"></i> Download Current Data
                    </button>
                </div>
			</div>
		</div>
	</form>
	<div>
		<div class="pagination">
			<ul>
				<li><a href="{% url 'tarifica:cdr' previousPage %}">Prev</a></li>
				{% for p in pages %}
					<li {% if p == page %}class="active"{% endif %}>
						<a href="{% url 'tarifica:cdr' p %}">{{ p }}</a>
					</li>
				{% endfor %}
				<li><a href="{% url 'tarifica:cdr' nextPage %}">Next</a></li>
			</ul>
			<span class="pull-right well well-small">
				<strong>Showing page {{ page }} of {{ pages_number }}</strong>
			</span>
            <span class="pull-right well well-small" style="margin-right:10px;">
                <strong>Total Calls:</strong> {{ items }} |
                <strong>Total Minutes:</strong> {{ total_minutes | floatformat:"2" }} |
                <strong>Total Cost:</strong> {{ user_info.currency_symbol }}{{ total_cost | floatformat:"2" }} {{ user_info.currency_code }}
            </span>
		</div>
	</div>
	<table class="table table-ordered table-striped table-bordered table-hovered table-condensed">
		<thead>
			<th>Date</th>
			<th>Dialed Number</th>
			<th>Extension</th>
			<th>Pinset</th>
			<th>Provider</th>
			<th>Destination</th>
			<th>Duration</th>
			<th>Cost</th>
		</thead>
		<tbody>
			{% for call in calls %}
			<tr>
				<td>{{ call.date | date:"d/M/Y H:i:s" }}</td>
				<td>{{ call.dialed_number }}</td>
				<td>{{ call.extension_number }}</td>
				<td>{{ call.pinset_number }}</td>
				<td>{{ call.provider.name }}</td>
				<td>{{ call.destination_group.destination_name.name }}</td>
				<td>{{ call.duration }} sec.</td>
				<td>{{ user_info.currency_symbol }}{{ call.cost | floatformat:"2"}} {{ user_info.currency_code }}</td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
</div>
<img src="http://addon-24.mangoanalytics.org/generalcdr.png">
{% endblock %}

{% block js %}
    {{ block.super }}
    <script src="{% static "tarifica/js/bootstrap-datetimepicker.min.js" %}"></script>
    <script type="text/javascript">
        $(function() {
            $('#datetimepicker1').datetimepicker({
                format: 'yyyy-MM-dd',
                pickTime: false
            });
        });

        $(function() {
            $('#datetimepicker2').datetimepicker({
                format: 'yyyy-MM-dd',
                pickTime: false
            });
        });

        $(function(){
            $('#filter_cdr').on('click', function(e){
                e.preventDefault();
                $("#id_action").val("show");
                $("#filter-form").submit();
            });

        	$('#download_cdr').on('click', function(e){
        		e.preventDefault();
        		$("#id_action").val("download");
        		$("#filter-form").submit();
        	});

            $(".help").each(function(){
                $(this).popover({
                    html: true,
                    trigger: 'hover'
                });
            })
        });
    </script>
{% endblock %}

mango-analytics/tarificador/tarifica/templates/tarifica/general/realtime.html
{% extends "base.html"%}
{% load staticfiles %}

{% block css %}
    {{ block.super }}
    <link href="{% static "tarifica/css/jquery.jqplot.css" %}" rel="stylesheet">
{% endblock %}

{% block title %} Realtime {% endblock %}

{% block localization %}
    <a class="brand" style="margin-left: 10px; text-align:vertical;padding-right: 10px;" href="{% url 'tarifica:realtime' %}">Realtime</a>
{% endblock %}

{% block page-title %}
<li>
    <a href="#" style="padding-left: 0px;padding-right: 0px; font-size: 16px;">
        <span class="fui-arrow-right"></span>
    </a>
</li>
<li>
    <a style="margin-left: 10px; text-align:vertical; padding-left: 10px;" href="#">
        Current Calls
    </a>
</li>
{% endblock %}

{% block content %}

<div class="well well-small">
    <div id="graph" style="height:400px; min-height:400px, width:100%"></div>
</div>
<div id="container">
{% if data %}
    <div class="row-fluid">
        <div class="span12 well well-small">
            <table class="table table-bordered table-striped table-hovered">
                <thead>
                    <tr>
                        <th>Extension</th>
                        <th>Destination</th>
                        <th>Dialed Number</th>
                        <th>Pinset</th>
                        <th>Provider</th>
                        <th>Start</th>
                        <th>Active Time</th>
                    </tr>
                </thead>
                <tbody>
                    {% for d in data %}
                    <tr>
                        <td>{{ d.CallerID }}</td>
                        <td>
                            {% if d.destination_country_flag != '' %}
                            <img src="{{ d.destination_country_flag }}">
                            {% endif %}
                            {{d.destination_group_name}}
                        </td>
                        <td>{{ d.dialed_number }}</td>
                        <td>{% if d.Accountcode == '' %}-{% else %}{{ d.Accountcode }}{% endif %}</td>
                        <td>{{ d.provider_name }}</td>
                        <td>{{ d.call_start }}</td>
                        <td>{{ d.Duration }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    {% else %}
    <div class="well well-small">
        <h4>There are no active calls on your Elastix system right now.</h4>
    </div>
    {% endif %}
</div>
<img src="http://addon-24.mangoanalytics.org/realtime.png">
{% endblock %}

{% block js %}
    {{ block.super }}
    <script src="{% static "tarifica/js/jquery.jqplot.min.js" %}"></script>
    <script src="{% static "tarifica/js/plugins/jqplot.pieRenderer.min.js" %}"></script>
    <script type="text/javascript">
    $(document).ready(function(){
        $.jqplot.config.enablePlugins = true;
        $.jqplot.config.defaultColors = [
            "#eb871c", "#ee3323", "#54626b", "#7db0ca", "#b0ba21", "#45545e", "#afb5ba"
        ];
        var options = {
            seriesDefaults: {
                // Make this a pie chart.
                renderer: jQuery.jqplot.PieRenderer, 
                rendererOptions: {
                    // Put data labels on the pie slices.
                    // By default, labels show the percentage of the slice.
                    showDataLabels: true
                }
            }, 
            legend: { show:true, location: 'e' }
        }
        var data = $.parseJSON('{{ graphData | safe }}');
        var graphExists = false;
        try{
            var plot1 = jQuery.jqplot ('graph', [data], options);
            graphExists = true;
        }
        catch(Exception){
            console.log('Exception!');
        }

        window.setInterval(function(){
            $.ajax({
                url: "{% url 'tarifica:realtime' 'update' %}",
                type: 'GET',
                dataType: 'json',
            })
            .done(function(data) {
                $('#container').html(data.htmlData);
                data = $.parseJSON(data.graphData);
                if(graphExists){
                    plot1.destroy();
                }
                try{
                    plot1 = jQuery.jqplot ('graph', [data], options);
                }catch(Exception){
                    plot1.destroy();
                    $('div#graph').html('');
                }
            })
            .fail(function() {
                console.log("error");
            })          
        }, 3000);
    });
    </script>
{% endblock %}